% Central configuration for model parameters, constants, and project paths.

classdef ExoConfig < handle
    properties (Constant)
        % ---------------- System Parameters ----------------
        FS = 100;               % Sampling Frequency (Hz)
        WINDOW_SIZE = 100;      % Sliding window size (1.0 second)
        STEP_SIZE = 50;         % Sliding window step (0.5 second)
        
        % ---------------- File Paths -----------------------
        % Uses relative paths from the project root
        FILE = struct(...
            'SVM_MODEL', fullfile('models', 'Binary_SVM_Model_hugadb_only.mat'), ...
            'BINARY_LSTM', fullfile('models', 'Binary_LSTM_Network.mat'), ...
            'BINARY_LSTM_USCHAD', fullfile('models', 'Binary_LSTM_Network_usc_had_only.mat'), ...
            'BINARY_LSTM_HUGADB', fullfile('models', 'Binary_LSTM_Network_hugadb_only.mat'), ...
            'MULTICLASS_LSTM', fullfile('models', 'Multiclass_LSTM_hugadb.mat'), ...
            'MULTICLASS_LSTM_HUGADB', fullfile('models', 'Multiclass_LSTM_hugadb.mat'), ...
            'MULTICLASS_LSTM_USCHAD', fullfile('models', 'Multiclass_LSTM_usc_had.mat'), ...
            'MULTICLASS_SVM', fullfile('models', 'Multiclass_SVM_ECOC_hugadb.mat'), ...
            'MULTICLASS_SVM_HUGADB', fullfile('models', 'Multiclass_SVM_ECOC_hugadb.mat'), ...
            'MULTICLASS_SVM_USCHAD', fullfile('models', 'Multiclass_SVM_ECOC_usc_had.mat'), ...
            'USCHAD_DATA', fullfile('data', 'USC-HAD', 'usc_had_dataset.mat'), ...
            'HUGADB_DATA', fullfile('data', 'HuGaDB', 'hugadb_dataset.mat') ...
        );
        
        % ---------------- Dataset Definitions --------------
        DS = struct(...
            'USCHAD', struct(...
                'ACTIVE_LABELS', [1, 2, 3, 4, 5, 6, 7], ...
                'NON_ACTIVE_LABELS', [8, 9, 10, 11, 12], ...
                'WALKING_LABELS', [1, 2, 3, 4, 5, 6, 7], ...
                'NON_WALKING_LABELS', [8, 9, 10, 11, 12] ...
            ), ...
            'HUGADB', struct(...
                'ACTIVE_LABELS', [1, 2, 3, 4, 6, 7, 9], ...
                'NON_ACTIVE_LABELS', [5, 8, 10, 11, 12], ...
                'WALKING_LABELS', [1, 2, 3, 4, 6, 7, 9], ...
                'NON_WALKING_LABELS', [5, 8, 10, 11, 12] ...
            ) ...
        );
        
        % ---------------- State Machine --------------------
        STATE_STANDING = 0;
        STATE_WALKING = 1;
        
        % ---------------- Dataset Policy -------------------
        TRAINING = struct( ...
            'DEFAULT_INCLUDE_USCHAD', false, ...
            'DEFAULT_INCLUDE_HUGADB', true ...
        );
        HUGADB = struct( ...
            'HELDOUT_SUBJECTS', {{'06', '08'}}, ...
            'DEFAULT_SIM_SUBJECT', '06', ...
            'DEFAULT_SIM_SESSION', '' ...
        );
        
        % ---------------- Simulation -----------------------
        SIMULATION = struct( ...
            'SOURCE', 'hugadb', ...
            'KALMAN_ENABLED', true, ...
            'KALMAN_IMU_LABEL', 'lt' ...
        );

        % ---------------- Locomotion features (train + inference) ------------
        % HuGaDB (`hugadb_dataset.mat` from LoadHuGaDB) provides 6 IMUs per row; Features.m outputs 5 scalars per IMU.
        % USC-HAD and on-device inference use one IMU → pad to N_IMU_SLOTS * FEATURES_PER_IMU.
        LOCOMOTION = struct( ...
            'N_IMU_SLOTS', 6, ...
            'FEATURES_PER_IMU', 5 ...
        );
    end
end
