function report = HuGaDBInitQualityReport()
% HuGaDBInitQualityReport  Create an empty HuGaDB quality report accumulator.

    report = struct( ...
        'nSessionsScanned', 0, ...
        'nSessionsAccepted', 0, ...
        'nSessionsSkipped', 0, ...
        'nWindowsScanned', 0, ...
        'nWindowsAccepted', 0, ...
        'nWindowsSkipped', 0, ...
        'sessionReasons', struct(), ...
        'windowReasons', struct() ...
    );
end
